# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  param_fetcher_listener: force
  view:
    formats:
      json: true
    view_response_listener:  true
  exception:
    exception_controller: 'fos_rest.exception.controller:showAction'
  format_listener:
    rules:
    - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors
  routing_loader:
    include_format: false